# Configurations for the uvicorn server and cookie policy
[server_config]
host = "0.0.0.0"
port = 8010
reload = true
# e.g. ["*"] to allow any host, ["*.example.com"] to allow all from wildcard, ["*.example.com", "192.168.0.5"] or others
allowed_hosts = ["*"]
# If enabled, the cookies will be set to secure so only https connections will work
secure_only = false
# If using reverse Proxy like NGINX, you should enable allow proxy and set the IP adresses of the proxy
# This enables the correct IP's in the log instead of the proxies IP
allow_proxy = false
proxy_ips = []
